import json
import os
import logging
from typing import Dict, Any, Optional

from app.modules.final_output.schemas import FinalReport, LLMReportOutput
from app.modules.final_output.exceptions import ReportRenderException

logger = logging.getLogger(__name__)


def build_final_report_from_llm(llm_report: LLMReportOutput) -> FinalReport:
    return FinalReport(
        title="Final AutoML Report for Materials Property Prediction",
        executive_summary=llm_report.executive_summary,
        task_overview=llm_report.task_overview,
        dataset_summary=llm_report.dataset_summary,
        workflow_summary=llm_report.workflow_summary,
        feature_engineering_summary=llm_report.feature_engineering_summary,
        model_search_summary=llm_report.model_search_summary,
        final_model_summary=llm_report.final_model_summary,
        metric_summary=llm_report.metric_summary,
        interpretability_summary=llm_report.interpretability_summary,
        material_insight_summary=llm_report.material_insight_summary,
        limitations_and_risks=llm_report.limitations_and_risks,
        reproducibility_notes=llm_report.reproducibility_notes,
        artifact_summary=llm_report.artifact_summary,
        next_steps=llm_report.next_steps,
    )


def build_fallback_report(
    final_model_id: str = "",
    primary_metric: str = "",
    primary_metric_value: Optional[float] = None,
) -> FinalReport:
    return FinalReport(
        title="Final AutoML Report for Materials Property Prediction",
        executive_summary=(
            f"An AutoML pipeline was executed for materials property prediction. "
            f"The final selected model is {final_model_id}. "
            f"The primary metric ({primary_metric}) achieved a value of {primary_metric_value}."
            if primary_metric_value is not None
            else f"An AutoML pipeline was executed for materials property prediction. "
            f"The final selected model is {final_model_id}."
        ),
        task_overview="AutoML task for materials property prediction.",
        dataset_summary="Dataset was loaded and profiled by the system.",
        workflow_summary="The AutoML workflow included feature engineering, model search, HPO, training, evaluation, and interpretability analysis.",
        feature_engineering_summary="Feature engineering was performed automatically.",
        model_search_summary="Model search was conducted across multiple model families.",
        final_model_summary=f"Final model: {final_model_id}.",
        metric_summary=f"Primary metric ({primary_metric}): {primary_metric_value}.",
        interpretability_summary="Interpretability analysis was performed. See detailed results in the interpretability section.",
        material_insight_summary="Material insights were generated by LLM analysis of feature importance patterns.",
        limitations_and_risks=(
            "This report was generated using a system template fallback. "
            "LLM-generated report was unavailable. "
            "Model interpretations are associations, not causal conclusions."
        ),
        reproducibility_notes="Reproducibility summary is available in the output package.",
        artifact_summary="Artifacts include model file, predictions, and interpretability results.",
        next_steps="Review the final report, validate model performance, and consider domain expert review.",
    )


def render_json_report(report: FinalReport, output_path: str) -> str:
    try:
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            json.dump(report.model_dump(), f, indent=2, ensure_ascii=False)
        logger.info("JSON report rendered to %s", output_path)
        return output_path
    except Exception as e:
        logger.error("Failed to render JSON report: %s", str(e))
        raise ReportRenderException(f"JSON report render failed: {str(e)}")


def render_markdown_report(report: FinalReport, output_path: str) -> str:
    try:
        md = _build_markdown(report)
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(md)
        logger.info("Markdown report rendered to %s", output_path)
        return output_path
    except Exception as e:
        logger.error("Failed to render Markdown report: %s", str(e))
        raise ReportRenderException(f"Markdown report render failed: {str(e)}")


def _build_markdown(report: FinalReport) -> str:
    lines = [
        f"# {report.title}",
        "",
        "## Executive Summary",
        "",
        report.executive_summary,
        "",
        "## Task Overview",
        "",
        report.task_overview,
        "",
        "## Dataset Summary",
        "",
        report.dataset_summary,
        "",
        "## Workflow Summary",
        "",
        report.workflow_summary,
        "",
        "## Feature Engineering Summary",
        "",
        report.feature_engineering_summary,
        "",
        "## Model Search Summary",
        "",
        report.model_search_summary,
        "",
        "## Final Model Summary",
        "",
        report.final_model_summary,
        "",
        "## Metric Summary",
        "",
        report.metric_summary,
        "",
        "## Interpretability Summary",
        "",
        report.interpretability_summary,
        "",
        "## Material Insight Summary",
        "",
        report.material_insight_summary,
        "",
        "## Limitations and Risks",
        "",
        report.limitations_and_risks,
        "",
        "## Reproducibility Notes",
        "",
        report.reproducibility_notes,
        "",
        "## Artifact Summary",
        "",
        report.artifact_summary,
        "",
        "## Next Steps",
        "",
        report.next_steps,
        "",
        "---",
        "",
        "*Report generated by MLAgent Final Output module.*",
    ]
    return "\n".join(lines)
