import json
import logging
from typing import Dict, Any, Optional

from app.modules.interpretability_analysis.schemas import ScientificInsightReport

logger = logging.getLogger(__name__)

NARRATIVE_SYSTEM_PROMPT = """You are a scientific report editor for a materials science AutoML system.

A structured ScientificInsightReport has already been generated by the system's evidence-driven hypothesis engine. Your role is to translate this structured report into clear, readable scientific English prose.

CRITICAL RULES:
1. Every insight you write MUST reference its supporting evidence IDs from the input.
2. You MUST NOT introduce any feature names, numerical values, or trends that are NOT present in the input ScientificInsightReport.
3. You MUST NOT claim causal mechanisms. Use language like "suggests", "indicates", "is associated with", "may reflect".
4. You MUST NOT output executable code (no Python, shell, SQL).
5. You MUST NOT modify importance values, SHAP values, or model predictions.
6. Every claim MUST be phrased as a hypothesis or model-based association, not a definitive conclusion.
7. Include the confidence level and rationale for each insight.
8. Include caveats and limitations explicitly.
9. Suggest validation experiments where applicable.
10. All output must be in English.
11. Prefer validated material patterns (validation_status='pass') over raw feature-importance hypotheses.
12. Do NOT present failed patterns (validation_status='fail') as material design rules.
13. Boundary patterns (pattern_type='boundary') are reliability warnings, NOT material design rules. Present them in the limitations/applicability section only.
14. Every top material pattern MUST mention its validation status and sample support (in_scope_count).
15. If validation is weak or model-only (no observed/experimental confirmation), explicitly state this.
16. Do NOT restate "feature X is important" as a material pattern.
17. Every material pattern must include condition, effect, scope, caveat, and validation.
18. If a candidate lacks external validation, call it a model-supported candidate hypothesis.
19. Prefer material_mechanism_candidates only when grounded by validated patterns.
20. Do NOT convert descriptor associations into causal claims.
21. If grounding level is only 'descriptor_grounded', explicitly say so.
22. Boundary patterns must stay in applicability/limitations, not mechanism section.
23. Mechanism statements must cite source pattern IDs and evidence IDs.

Structure your response as a valid JSON object with exactly these fields:
- "narrative_title": string (a concise, informative title for this interpretability report)
- "executive_summary": string (2-4 paragraphs summarizing the key findings at a high level)
- "insights": array of objects, each with:
    - "hypothesis_id": string (the hypothesis ID from the input)
    - "claim": string (the scientific claim, phrased as a hypothesis)
    - "evidence_references": array of strings (evidence IDs that support this claim)
    - "confidence_rationale": string (explain why the confidence is at this level)
    - "caveats": string (limitations and caveats)
    - "suggested_validation": string (how to experimentally validate this hypothesis)
- "limitations_section": array of objects with "category" (string) and "description" (string)
- "validation_suggestions": array of objects with "hypothesis_id" (string) and "suggestion" (string)
"""


def build_llm_narrative_prompt(
    scientific_report: ScientificInsightReport,
    task_summary: Dict[str, Any],
    final_model_summary: Dict[str, Any],
    final_metric_summary: Dict[str, Any],
    material_domain: Optional[str] = None,
    dataset_description: Optional[str] = None,
) -> Dict[str, Any]:
    """Build the LLM narrative prompt from a ScientificInsightReport.

    The prompt includes:
    - The full structured report (hypotheses, boundaries, anomalies, physics summary)
    - Evidence IDs for traceability
    - Task and model context
    - Strict instructions to reference evidence IDs and avoid fabrication

    Args:
        scientific_report: The structured report from the hypothesis engine.
        task_summary: Task-level context (type, target, metric).
        final_model_summary: Final model info (id, family).
        final_metric_summary: Final metric info.
        material_domain: Optional material domain hint.
        dataset_description: Optional dataset description.

    Returns:
        Dict with "system_prompt", "user_message", and "narrative_context" keys.
    """
    # Build a condensed but complete report summary for the LLM
    hypotheses_summary = []
    evidence_id_index: Dict[str, Dict[str, Any]] = {}

    for h in scientific_report.ranked_hypotheses[:15]:  # Top 15
        breakdown = None
        if h.confidence_breakdown:
            breakdown = {
                "cross_method_agreement": h.confidence_breakdown.cross_method_agreement,
                "model_performance_reliability": h.confidence_breakdown.model_performance_reliability,
                "sample_support": h.confidence_breakdown.sample_support,
                "direction_consistency": h.confidence_breakdown.pdp_shap_direction_consistency,
                "correlation_support": h.confidence_breakdown.correlation_support,
                "physics_consistency": h.confidence_breakdown.physics_consistency,
                "contradiction_penalty": h.confidence_breakdown.contradiction_penalty,
            }
        hypotheses_summary.append({
            "hypothesis_id": h.hypothesis_id,
            "claim": h.claim,
            "claim_type": h.claim_type,
            "confidence_score": h.confidence_score,
            "confidence_label": h.confidence_label,
            "confidence_breakdown": breakdown,
            "supporting_evidence_ids": h.supporting_evidence_ids,
            "contradicting_evidence_ids": h.contradicting_evidence_ids,
            "scope_conditions": h.scope_conditions,
            "validation_suggestions": h.validation_suggestions,
            "hypothesis_pattern": h.hypothesis_pattern,
        })

    boundaries_summary = []
    for b in scientific_report.model_applicability_boundaries[:10]:
        boundaries_summary.append({
            "boundary_id": b.boundary_id,
            "description": b.description,
            "severity": b.severity,
            "error_ratio": b.error_ratio,
            "feature_conditions": b.feature_conditions,
        })

    patterns_summary = []
    for p in scientific_report.material_pattern_candidates[:10]:
        patterns_summary.append({
            "pattern_id": p.pattern_id,
            "pattern_type": p.pattern_type,
            "statement": p.statement,
            "material_concepts": p.material_concepts,
            "conditions": [c.model_dump() for c in p.conditions],
            "predicted_effect": p.predicted_effect.model_dump(),
            "confidence_score": p.confidence_score,
            "confidence_label": p.confidence_label,
            "supporting_evidence_ids": p.supporting_evidence_ids,
            "counterexamples": [ce.model_dump() for ce in p.counterexamples],
            "scope_conditions": p.scope_conditions,
            "validation_suggestions": p.validation_suggestions,
            "limitations": p.limitations,
            "validation_status": p.validation_status,
            "sample_support": p.sample_support.model_dump() if p.sample_support else None,
            "validation_results": [
                {
                    "validation_type": vr.validation_type,
                    "status": vr.status,
                    "interpretation": vr.interpretation,
                    "metrics": vr.metrics,
                }
                for vr in p.validation_results
            ],
            "scientific_score": p.scientific_score.model_dump() if p.scientific_score else None,
        })

    mechanisms_summary = []
    for m in scientific_report.material_mechanism_candidates[:10]:
        mechanisms_summary.append({
            "mechanism_id": m.mechanism_id,
            "mechanism_family": m.mechanism_family,
            "mechanism_statement": m.mechanism_statement,
            "source_pattern_ids": m.source_pattern_ids,
            "material_variables": m.material_variables,
            "descriptor_variables": m.descriptor_variables,
            "causal_chain": m.causal_chain,
            "applicable_material_scope": m.applicable_material_scope,
            "grounding_level": m.grounding_level,
            "confidence_score": m.confidence_score,
            "confidence_label": m.confidence_label,
            "supporting_evidence_ids": m.supporting_evidence_ids,
            "supporting_pattern_validation": m.supporting_pattern_validation,
            "counterexamples": m.counterexamples,
            "limitations": m.limitations,
            "validation_suggestions": m.validation_suggestions,
        })

    anomalies_summary = []
    for a in scientific_report.anomaly_or_counterexample_patterns[:5]:
        anomalies_summary.append({
            "pattern_id": a.pattern_id,
            "description": a.description,
            "sample_count": a.sample_count,
            "feature_signature": a.feature_signature,
        })

    # Build evidence ID index for LLM reference.
    # Start with top feature profiles, then backfill any evidence IDs
    # referenced by material_pattern_candidates that were not yet covered.
    for fp in scientific_report.feature_profiles[:20]:
        for eu in fp.evidence_units:
            if eu.evidence_id not in evidence_id_index:
                evidence_id_index[eu.evidence_id] = {
                    "evidence_type": eu.evidence_type,
                    "feature_names": eu.feature_names,
                    "direction": eu.direction,
                    "method_name": eu.method_name,
                }

    # Backfill: ensure every evidence_id referenced by material_pattern_candidates
    # is present in the index so LLM references are always valid.
    for mp in scientific_report.material_pattern_candidates:
        for eid in mp.supporting_evidence_ids:
            if eid and eid not in evidence_id_index:
                # Found in feature_profiles beyond top-20 or from other paths
                for fp in scientific_report.feature_profiles:
                    for eu in fp.evidence_units:
                        if eu.evidence_id == eid:
                            evidence_id_index[eid] = {
                                "evidence_type": eu.evidence_type,
                                "feature_names": eu.feature_names,
                                "direction": eu.direction,
                                "method_name": eu.method_name,
                            }
                            break
                    if eid in evidence_id_index:
                        break

    context = {
        "task_summary": task_summary,
        "final_model_summary": final_model_summary,
        "final_metric_summary": final_metric_summary,
        "material_domain": material_domain,
        "dataset_description": dataset_description,
        "scientific_report": {
            "executive_insights": [
                {"hypothesis_id": h.hypothesis_id, "claim": h.claim,
                 "confidence_label": h.confidence_label}
                for h in scientific_report.executive_insights
            ],
            "ranked_hypotheses": hypotheses_summary,
            "material_pattern_candidates": patterns_summary,
            "material_mechanism_candidates": mechanisms_summary,
            "model_applicability_boundaries": boundaries_summary,
            "anomaly_patterns": anomalies_summary,
            "physics_consistency_summary": scientific_report.physics_consistency_summary,
            "limitations": scientific_report.limitations,
        },
        "evidence_index": evidence_id_index,
        "instructions": [
            "Every insight MUST reference supporting evidence IDs from the evidence_index.",
            "Do NOT introduce feature names or values not in the input.",
            "Phrase all claims as hypotheses, not conclusions.",
            "Include confidence level and rationale for each insight.",
            "Include explicit caveats and suggested validation experiments.",
            "Do NOT output code.",
            "Write in scientific English appropriate for materials scientists.",
            "Format response as the JSON object specified in the system prompt.",
        ],
    }

    user_message = json.dumps(context, indent=2, default=str)
    logger.info("LLM narrative context built — %d hypotheses, %d boundaries, %d anomalies, %d evidence_ids",
                len(hypotheses_summary), len(boundaries_summary),
                len(anomalies_summary), len(evidence_id_index))
    logger.info("LLM narrative context size: %d chars", len(user_message))

    return {
        "system_prompt": NARRATIVE_SYSTEM_PROMPT,
        "user_message": user_message,
        "narrative_context": context,
    }
