"""
Feature Preprocessing Capability Registry.

Defines the 12 core preprocessing capability groups that the Feature Preprocessing
LLM can select from when generating a PreprocessingPlan.

All operations reference capabilities defined here — no unregistered operations
may be executed. Each capability includes parameter schemas, fit scope, risk notes,
and fallback mappings.
"""
from typing import List, Optional, Dict, Any
from pydantic import BaseModel


class FPCapabilitySpec(BaseModel):
    capability_id: str
    display_name: str
    capability_group: str  # one of the 12 groups
    operation_type: str  # imputation | analysis | filtering | scaling | transformation | redundancy_filter | leakage_detection | feature_selection | group_policy | dimensionality_reduction | lineage | artifact_tracking
    status: str  # available | planned | disabled | experimental
    supported_feature_types: List[str] = ["numeric", "categorical", "boolean"]
    supported_feature_groups: List[str] = ["composition", "structure", "descriptor", "metadata", "generated"]
    requires_target: bool = False
    fit_scope: str = "dataset_profile_only"  # dataset_profile_only | train_only | fold_only
    allowed_pipeline_positions: List[str] = []
    parameters_schema: dict = {}
    default_parameters: dict = {}
    risk_notes: List[str] = []
    fallback_capability_ids: List[str] = []
    version: str = "1.0.0"


# ====================================================================
# 12 Capability Groups Definition
# ====================================================================

CAPABILITY_GROUPS = {
    "missing_value_handling": "缺失值处理能力",
    "missingness_analysis": "缺失机制分析能力",
    "low_information_filtering": "常量、近常量与低信息量特征过滤",
    "scaling_normalization": "缩放与标准化能力",
    "distribution_transformation": "偏态分布与数值变换能力",
    "correlation_collinearity": "相关性、共线性与冗余特征处理",
    "leakage_detection": "目标泄漏与标识列检测",
    "feature_selection": "特征选择能力",
    "feature_group_policy": "特征组策略能力",
    "dimensionality_reduction": "降维能力",
    "interpretability_preservation": "可解释性保护能力",
    "artifact_reproducibility": "Artifact与可重复性能力",
}

# ====================================================================
# Full Registry
# ====================================================================

PREPROCESSING_CAPABILITIES: List[FPCapabilitySpec] = [
    # ===== Group 1: Missing Value Handling =====
    FPCapabilitySpec(
        capability_id="missing_rate_filter",
        display_name="缺失率过滤 (Missing Rate Filter)",
        capability_group="missing_value_handling",
        operation_type="filtering",
        status="available",
        supported_feature_types=["numeric", "categorical", "boolean"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=False,
        fit_scope="dataset_profile_only",
        allowed_pipeline_positions=["before_scaling"],
        parameters_schema={"max_missing_ratio": {"type": "float", "minimum": 0.0, "maximum": 1.0, "default": 0.5}},
        default_parameters={"max_missing_ratio": 0.5},
        risk_notes=["高缺失率阈值可能导致丢失关键材料特征"],
        fallback_capability_ids=["median_imputer"],
        version="1.0.0",
    ),
    FPCapabilitySpec(
        capability_id="median_imputer",
        display_name="中位数插补 (Median Imputer)",
        capability_group="missing_value_handling",
        operation_type="imputation",
        status="available",
        supported_feature_types=["numeric"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=False,
        fit_scope="fold_only",
        allowed_pipeline_positions=["before_scaling", "after_imputation"],
        parameters_schema={"strategy": {"type": "string", "enum": ["median"], "default": "median"}},
        default_parameters={"strategy": "median"},
        risk_notes=["对长尾分布特征的插补可能偏离", "必须fold-safe"],
        fallback_capability_ids=["mean_imputer"],
        version="1.0.0",
    ),
    FPCapabilitySpec(
        capability_id="mean_imputer",
        display_name="均值插补 (Mean Imputer)",
        capability_group="missing_value_handling",
        operation_type="imputation",
        status="available",
        supported_feature_types=["numeric"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=False,
        fit_scope="fold_only",
        allowed_pipeline_positions=["before_scaling", "after_imputation"],
        parameters_schema={"strategy": {"type": "string", "enum": ["mean"], "default": "mean"}},
        default_parameters={"strategy": "mean"},
        risk_notes=["受极端值影响", "必须fold-safe"],
        fallback_capability_ids=["median_imputer"],
        version="1.0.0",
    ),
    FPCapabilitySpec(
        capability_id="most_frequent_imputer",
        display_name="众数插补 (Most Frequent Imputer)",
        capability_group="missing_value_handling",
        operation_type="imputation",
        status="available",
        supported_feature_types=["categorical", "boolean"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=False,
        fit_scope="fold_only",
        allowed_pipeline_positions=["before_scaling", "after_imputation"],
        parameters_schema={"strategy": {"type": "string", "enum": ["most_frequent"], "default": "most_frequent"}},
        default_parameters={"strategy": "most_frequent"},
        risk_notes=["对类别不平衡特征需谨慎", "必须fold-safe"],
        fallback_capability_ids=["constant_imputer"],
        version="1.0.0",
    ),
    FPCapabilitySpec(
        capability_id="constant_imputer",
        display_name="常数插补 (Constant Imputer)",
        capability_group="missing_value_handling",
        operation_type="imputation",
        status="available",
        supported_feature_types=["numeric", "categorical"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=False,
        fit_scope="fold_only",
        allowed_pipeline_positions=["before_scaling", "after_imputation"],
        parameters_schema={"fill_value": {"type": "any", "default": 0}},
        default_parameters={"fill_value": 0},
        risk_notes=["引入人工分布偏差", "仅用于特定领域知识场景"],
        fallback_capability_ids=["median_imputer"],
        version="1.0.0",
    ),
    FPCapabilitySpec(
        capability_id="missing_indicator",
        display_name="缺失指示器 (Missing Indicator)",
        capability_group="missing_value_handling",
        operation_type="imputation",
        status="available",
        supported_feature_types=["numeric", "categorical"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=False,
        fit_scope="fold_only",
        allowed_pipeline_positions=["before_scaling", "after_imputation"],
        parameters_schema={"add_indicator": {"type": "boolean", "default": True}},
        default_parameters={"add_indicator": True},
        risk_notes=["增加特征维度", "缺失模式必须 fold 内一致"],
        fallback_capability_ids=[],
        version="1.0.0",
    ),
    FPCapabilitySpec(
        capability_id="groupwise_imputer",
        display_name="分组插补 (Group-wise Imputer)",
        capability_group="missing_value_handling",
        operation_type="imputation",
        status="available",
        supported_feature_types=["numeric"],
        supported_feature_groups=["composition", "structure", "descriptor"],
        requires_target=False,
        fit_scope="fold_only",
        allowed_pipeline_positions=["before_scaling", "after_imputation"],
        parameters_schema={"per_group_strategy": {"type": "object", "default": {}}},
        default_parameters={"per_group_strategy": {}},
        risk_notes=["需要明确feature group划分", "分组内样本数不足时可能退化"],
        fallback_capability_ids=["median_imputer"],
        version="1.0.0",
    ),

    # ===== Group 2: Missingness Analysis =====
    FPCapabilitySpec(
        capability_id="missingness_profile_analyzer",
        display_name="全局缺失画像分析 (Missingness Profile Analyzer)",
        capability_group="missingness_analysis",
        operation_type="analysis",
        status="available",
        supported_feature_types=["numeric", "categorical", "boolean"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=False,
        fit_scope="dataset_profile_only",
        allowed_pipeline_positions=["before_scaling"],
        parameters_schema={},
        default_parameters={},
        risk_notes=["仅分析不执行操作", "分析结果用于LLM决策"],
        fallback_capability_ids=[],
        version="1.0.0",
    ),
    FPCapabilitySpec(
        capability_id="missing_by_feature_group_analyzer",
        display_name="按特征组缺失分析 (Missing by Feature Group Analyzer)",
        capability_group="missingness_analysis",
        operation_type="analysis",
        status="available",
        supported_feature_types=["numeric", "categorical", "boolean"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=False,
        fit_scope="dataset_profile_only",
        allowed_pipeline_positions=["before_scaling"],
        parameters_schema={},
        default_parameters={},
        risk_notes=["需要feature group信息"],
        fallback_capability_ids=["missingness_profile_analyzer"],
        version="1.0.0",
    ),
    FPCapabilitySpec(
        capability_id="missing_pattern_analyzer",
        display_name="缺失模式分析 (Missing Pattern Analyzer)",
        capability_group="missingness_analysis",
        operation_type="analysis",
        status="available",
        supported_feature_types=["numeric", "categorical", "boolean"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=False,
        fit_scope="dataset_profile_only",
        allowed_pipeline_positions=["before_scaling"],
        parameters_schema={},
        default_parameters={},
        risk_notes=["大特征矩阵时计算成本较高"],
        fallback_capability_ids=["missingness_profile_analyzer"],
        version="1.0.0",
    ),
    FPCapabilitySpec(
        capability_id="missing_target_correlation_checker",
        display_name="缺失-目标相关检查 (Missing-Target Correlation Checker)",
        capability_group="missingness_analysis",
        operation_type="analysis",
        status="available",
        supported_feature_types=["numeric"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=True,
        fit_scope="dataset_profile_only",
        allowed_pipeline_positions=["before_scaling"],
        parameters_schema={},
        default_parameters={},
        risk_notes=["需要target availability", "仅作分析不参与CV"],
        fallback_capability_ids=[],
        version="1.0.0",
    ),
    FPCapabilitySpec(
        capability_id="missing_not_at_random_flagger",
        display_name="MNAR风险标记 (Missing Not At Random Flagger)",
        capability_group="missingness_analysis",
        operation_type="analysis",
        status="available",
        supported_feature_types=["numeric"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=True,
        fit_scope="dataset_profile_only",
        allowed_pipeline_positions=["before_scaling"],
        parameters_schema={},
        default_parameters={},
        risk_notes=["MNAR检测仅为启发式方法", "不能替代领域知识"],
        fallback_capability_ids=[],
        version="1.0.0",
    ),

    # ===== Group 3: Low Information Filtering =====
    FPCapabilitySpec(
        capability_id="constant_feature_filter",
        display_name="常量特征过滤 (Constant Feature Filter)",
        capability_group="low_information_filtering",
        operation_type="filtering",
        status="available",
        supported_feature_types=["numeric", "categorical", "boolean"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=False,
        fit_scope="dataset_profile_only",
        allowed_pipeline_positions=["before_scaling"],
        parameters_schema={"strict": {"type": "boolean", "default": False}},
        default_parameters={"strict": False},
        risk_notes=["对于小样本可能过滤材料学重要特征"],
        fallback_capability_ids=[],
        version="1.0.0",
    ),
    FPCapabilitySpec(
        capability_id="near_constant_feature_filter",
        display_name="近常量特征过滤 (Near-Constant Feature Filter)",
        capability_group="low_information_filtering",
        operation_type="filtering",
        status="available",
        supported_feature_types=["numeric"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=False,
        fit_scope="dataset_profile_only",
        allowed_pipeline_positions=["before_scaling"],
        parameters_schema={"threshold": {"type": "float", "minimum": 0.0, "maximum": 1.0, "default": 0.95}},
        default_parameters={"threshold": 0.95},
        risk_notes=["阈值选择影响材料特征保留", "建议默认0.95，材料任务可放宽"],
        fallback_capability_ids=[],
        version="1.0.0",
    ),
    FPCapabilitySpec(
        capability_id="low_variance_filter",
        display_name="低方差过滤 (Low Variance Filter)",
        capability_group="low_information_filtering",
        operation_type="filtering",
        status="available",
        supported_feature_types=["numeric"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=False,
        fit_scope="dataset_profile_only",
        allowed_pipeline_positions=["before_scaling"],
        parameters_schema={"threshold": {"type": "float", "minimum": 0.0, "default": 0.0}},
        default_parameters={"threshold": 0.0},
        risk_notes=["需要先缩放才能比较方差"],
        fallback_capability_ids=["constant_feature_filter"],
        version="1.0.0",
    ),
    FPCapabilitySpec(
        capability_id="low_unique_ratio_filter",
        display_name="低唯一值比例过滤 (Low Unique Ratio Filter)",
        capability_group="low_information_filtering",
        operation_type="filtering",
        status="available",
        supported_feature_types=["numeric", "categorical"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=False,
        fit_scope="dataset_profile_only",
        allowed_pipeline_positions=["before_scaling"],
        parameters_schema={"min_unique_ratio": {"type": "float", "minimum": 0.0, "maximum": 1.0, "default": 0.01}},
        default_parameters={"min_unique_ratio": 0.01},
        risk_notes=["二值特征可能被误删"],
        fallback_capability_ids=[],
        version="1.0.0",
    ),
    FPCapabilitySpec(
        capability_id="single_value_dominance_filter",
        display_name="单一值占比过高过滤 (Single Value Dominance Filter)",
        capability_group="low_information_filtering",
        operation_type="filtering",
        status="available",
        supported_feature_types=["numeric", "categorical"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=False,
        fit_scope="dataset_profile_only",
        allowed_pipeline_positions=["before_scaling"],
        parameters_schema={"max_dominance_ratio": {"type": "float", "minimum": 0.0, "maximum": 1.0, "default": 0.95}},
        default_parameters={"max_dominance_ratio": 0.95},
        risk_notes=["与near_constant阈值协同调整"],
        fallback_capability_ids=["near_constant_feature_filter"],
        version="1.0.0",
    ),

    # ===== Group 4: Scaling & Normalization =====
    FPCapabilitySpec(
        capability_id="standard_scaler",
        display_name="标准缩放 (Standard Scaler)",
        capability_group="scaling_normalization",
        operation_type="scaling",
        status="available",
        supported_feature_types=["numeric"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=False,
        fit_scope="fold_only",
        allowed_pipeline_positions=["after_imputation"],
        parameters_schema={"with_mean": {"type": "boolean", "default": True}, "with_std": {"type": "boolean", "default": True}},
        default_parameters={"with_mean": True, "with_std": True},
        risk_notes=["对强偏态分布效果不佳", "必须fold-safe"],
        fallback_capability_ids=["robust_scaler"],
        version="1.0.0",
    ),
    FPCapabilitySpec(
        capability_id="minmax_scaler",
        display_name="最小-最大缩放 (MinMax Scaler)",
        capability_group="scaling_normalization",
        operation_type="scaling",
        status="available",
        supported_feature_types=["numeric"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=False,
        fit_scope="fold_only",
        allowed_pipeline_positions=["after_imputation"],
        parameters_schema={"feature_range": {"type": "tuple", "default": [0, 1]}},
        default_parameters={"feature_range": [0, 1]},
        risk_notes=["对极端值敏感", "必须fold-safe"],
        fallback_capability_ids=["robust_scaler", "standard_scaler"],
        version="1.0.0",
    ),
    FPCapabilitySpec(
        capability_id="robust_scaler",
        display_name="鲁棒缩放 (Robust Scaler)",
        capability_group="scaling_normalization",
        operation_type="scaling",
        status="available",
        supported_feature_types=["numeric"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=False,
        fit_scope="fold_only",
        allowed_pipeline_positions=["after_imputation"],
        parameters_schema={"quantile_range": {"type": "tuple", "default": [25.0, 75.0]}},
        default_parameters={"quantile_range": [25.0, 75.0]},
        risk_notes=["对binary特征不适合", "必须fold-safe"],
        fallback_capability_ids=["standard_scaler"],
        version="1.0.0",
    ),
    FPCapabilitySpec(
        capability_id="maxabs_scaler",
        display_name="最大绝对值缩放 (MaxAbs Scaler)",
        capability_group="scaling_normalization",
        operation_type="scaling",
        status="available",
        supported_feature_types=["numeric"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=False,
        fit_scope="fold_only",
        allowed_pipeline_positions=["after_imputation"],
        parameters_schema={},
        default_parameters={},
        risk_notes=["保持稀疏性但受极端值影响", "必须fold-safe"],
        fallback_capability_ids=["robust_scaler"],
        version="1.0.0",
    ),
    FPCapabilitySpec(
        capability_id="no_scaling",
        display_name="不缩放 (No Scaling)",
        capability_group="scaling_normalization",
        operation_type="scaling",
        status="available",
        supported_feature_types=["numeric", "categorical", "boolean"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=False,
        fit_scope="dataset_profile_only",
        allowed_pipeline_positions=["after_imputation"],
        parameters_schema={},
        default_parameters={},
        risk_notes=["仅适合tree-based模型", "线性模型或距离模型不适用"],
        fallback_capability_ids=["standard_scaler"],
        version="1.0.0",
    ),
    FPCapabilitySpec(
        capability_id="groupwise_scaler",
        display_name="分组缩放 (Group-wise Scaler)",
        capability_group="scaling_normalization",
        operation_type="scaling",
        status="available",
        supported_feature_types=["numeric"],
        supported_feature_groups=["composition", "structure", "descriptor"],
        requires_target=False,
        fit_scope="fold_only",
        allowed_pipeline_positions=["after_imputation"],
        parameters_schema={"per_group_scaler": {"type": "object", "default": {}}},
        default_parameters={"per_group_scaler": {}},
        risk_notes=["分组缩放逻辑复杂", "必须fold-safe"],
        fallback_capability_ids=["standard_scaler"],
        version="1.0.0",
    ),
    FPCapabilitySpec(
        capability_id="model_family_aware_scaling_policy",
        display_name="模型族感知缩放策略 (Model-family-aware Scaling Policy)",
        capability_group="scaling_normalization",
        operation_type="scaling",
        status="available",
        supported_feature_types=["numeric"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=False,
        fit_scope="fold_only",
        allowed_pipeline_positions=["after_imputation"],
        parameters_schema={
            "linear_model_scaler": {"type": "string", "default": "standard_scaler"},
            "tree_model_scaler": {"type": "string", "default": "no_scaling"},
            "distance_model_scaler": {"type": "string", "default": "robust_scaler"},
        },
        default_parameters={
            "linear_model_scaler": "standard_scaler",
            "tree_model_scaler": "no_scaling",
            "distance_model_scaler": "robust_scaler",
        },
        risk_notes=["需要下游模型族信息", "多variant会增加artifact数量"],
        fallback_capability_ids=["standard_scaler"],
        version="1.0.0",
    ),

    # ===== Group 5: Distribution Transformation =====
    FPCapabilitySpec(
        capability_id="skewness_analyzer",
        display_name="偏态分析器 (Skewness Analyzer)",
        capability_group="distribution_transformation",
        operation_type="analysis",
        status="available",
        supported_feature_types=["numeric"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=False,
        fit_scope="dataset_profile_only",
        allowed_pipeline_positions=["before_scaling"],
        parameters_schema={"skewness_threshold": {"type": "float", "default": 1.0}},
        default_parameters={"skewness_threshold": 1.0},
        risk_notes=["仅分析不执行操作"],
        fallback_capability_ids=[],
        version="1.0.0",
    ),
    FPCapabilitySpec(
        capability_id="log_transform",
        display_name="对数变换 (Log Transform)",
        capability_group="distribution_transformation",
        operation_type="transformation",
        status="available",
        supported_feature_types=["numeric"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=False,
        fit_scope="fold_only",
        allowed_pipeline_positions=["before_scaling"],
        parameters_schema={"shift": {"type": "float", "default": 0.0}},
        default_parameters={"shift": 0.0},
        risk_notes=["仅适用于正值特征", "零值或负值需预先处理", "必须fold-safe"],
        fallback_capability_ids=["log1p_transform", "signed_log_transform"],
        version="1.0.0",
    ),
    FPCapabilitySpec(
        capability_id="log1p_transform",
        display_name="log(1+x)变换 (Log1p Transform)",
        capability_group="distribution_transformation",
        operation_type="transformation",
        status="available",
        supported_feature_types=["numeric"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=False,
        fit_scope="fold_only",
        allowed_pipeline_positions=["before_scaling"],
        parameters_schema={},
        default_parameters={},
        risk_notes=["仅适用于非负特征", "必须fold-safe"],
        fallback_capability_ids=["signed_log_transform"],
        version="1.0.0",
    ),
    FPCapabilitySpec(
        capability_id="signed_log_transform",
        display_name="有符号对数变换 (Signed Log Transform)",
        capability_group="distribution_transformation",
        operation_type="transformation",
        status="available",
        supported_feature_types=["numeric"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=False,
        fit_scope="fold_only",
        allowed_pipeline_positions=["before_scaling"],
        parameters_schema={},
        default_parameters={},
        risk_notes=["适用于包含负值的偏态特征", "必须fold-safe"],
        fallback_capability_ids=["power_transform_yeo_johnson"],
        version="1.0.0",
    ),
    FPCapabilitySpec(
        capability_id="power_transform_yeo_johnson",
        display_name="Yeo-Johnson变换 (Yeo-Johnson Power Transform)",
        capability_group="distribution_transformation",
        operation_type="transformation",
        status="available",
        supported_feature_types=["numeric"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=False,
        fit_scope="fold_only",
        allowed_pipeline_positions=["before_scaling"],
        parameters_schema={},
        default_parameters={},
        risk_notes=["可处理负值（优于Box-Cox）", "必须fold-safe"],
        fallback_capability_ids=["quantile_transform_normal"],
        version="1.0.0",
    ),
    FPCapabilitySpec(
        capability_id="quantile_transform_normal",
        display_name="分位数变换（正态）(Quantile Transform to Normal)",
        capability_group="distribution_transformation",
        operation_type="transformation",
        status="available",
        supported_feature_types=["numeric"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=False,
        fit_scope="fold_only",
        allowed_pipeline_positions=["before_scaling"],
        parameters_schema={"n_quantiles": {"type": "integer", "minimum": 10, "default": 1000}},
        default_parameters={"n_quantiles": 1000},
        risk_notes=["可能改变特征间的排序关系", "必须fold-safe"],
        fallback_capability_ids=["power_transform_yeo_johnson"],
        version="1.0.0",
    ),
    FPCapabilitySpec(
        capability_id="quantile_transform_uniform",
        display_name="分位数变换（均匀）(Quantile Transform to Uniform)",
        capability_group="distribution_transformation",
        operation_type="transformation",
        status="available",
        supported_feature_types=["numeric"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=False,
        fit_scope="fold_only",
        allowed_pipeline_positions=["before_scaling"],
        parameters_schema={"n_quantiles": {"type": "integer", "minimum": 10, "default": 1000}},
        default_parameters={"n_quantiles": 1000},
        risk_notes=["可能改变特征间的排序关系", "必须fold-safe"],
        fallback_capability_ids=["quantile_transform_normal"],
        version="1.0.0",
    ),
    FPCapabilitySpec(
        capability_id="auto_skewness_transform_selector",
        display_name="自适应偏态变换选择器 (Auto Skewness Transform Selector)",
        capability_group="distribution_transformation",
        operation_type="transformation",
        status="available",
        supported_feature_types=["numeric"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=False,
        fit_scope="fold_only",
        allowed_pipeline_positions=["before_scaling"],
        parameters_schema={"skewness_threshold": {"type": "float", "default": 1.0}, "max_method": {"type": "string", "default": "yeo_johnson"}},
        default_parameters={"skewness_threshold": 1.0, "max_method": "yeo_johnson"},
        risk_notes=["自动选择可能产生次优变换", "必须fold-safe"],
        fallback_capability_ids=["power_transform_yeo_johnson"],
        version="1.0.0",
    ),

    # ===== Group 6: Correlation & Collinearity =====
    FPCapabilitySpec(
        capability_id="pearson_correlation_filter",
        display_name="Pearson相关过滤 (Pearson Correlation Filter)",
        capability_group="correlation_collinearity",
        operation_type="redundancy_filter",
        status="available",
        supported_feature_types=["numeric"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=False,
        fit_scope="dataset_profile_only",
        allowed_pipeline_positions=["before_scaling", "after_imputation"],
        parameters_schema={"threshold": {"type": "float", "minimum": 0.0, "maximum": 1.0, "default": 0.95}},
        default_parameters={"threshold": 0.95},
        risk_notes=["只检测线性相关", "高相关性可能是领域真实的（如元素统计特征）"],
        fallback_capability_ids=["spearman_correlation_filter"],
        version="1.0.0",
    ),
    FPCapabilitySpec(
        capability_id="spearman_correlation_filter",
        display_name="Spearman相关过滤 (Spearman Correlation Filter)",
        capability_group="correlation_collinearity",
        operation_type="redundancy_filter",
        status="available",
        supported_feature_types=["numeric"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=False,
        fit_scope="dataset_profile_only",
        allowed_pipeline_positions=["before_scaling", "after_imputation"],
        parameters_schema={"threshold": {"type": "float", "minimum": 0.0, "maximum": 1.0, "default": 0.95}},
        default_parameters={"threshold": 0.95},
        risk_notes=["检测单调关系但忽略非线性关系", "计算成本高于Pearson"],
        fallback_capability_ids=["pearson_correlation_filter"],
        version="1.0.0",
    ),
    FPCapabilitySpec(
        capability_id="correlation_pair_reporter",
        display_name="高相关特征对报告 (Correlation Pair Reporter)",
        capability_group="correlation_collinearity",
        operation_type="analysis",
        status="available",
        supported_feature_types=["numeric"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=False,
        fit_scope="dataset_profile_only",
        allowed_pipeline_positions=["before_scaling"],
        parameters_schema={"threshold": {"type": "float", "default": 0.8}},
        default_parameters={"threshold": 0.8},
        risk_notes=["仅报告不执行删除", "供LLM决策参考"],
        fallback_capability_ids=[],
        version="1.0.0",
    ),
    FPCapabilitySpec(
        capability_id="variance_inflation_factor_filter",
        display_name="VIF过滤 (Variance Inflation Factor Filter)",
        capability_group="correlation_collinearity",
        operation_type="redundancy_filter",
        status="available",
        supported_feature_types=["numeric"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=False,
        fit_scope="dataset_profile_only",
        allowed_pipeline_positions=["before_scaling", "after_imputation"],
        parameters_schema={"vif_threshold": {"type": "float", "minimum": 1.0, "default": 10.0}},
        default_parameters={"vif_threshold": 10.0},
        risk_notes=["特征数大于样本数时VIF不可靠", "计算量为O(n_features^2)"],
        fallback_capability_ids=["pearson_correlation_filter"],
        version="1.0.0",
    ),
    FPCapabilitySpec(
        capability_id="hierarchical_correlation_clustering",
        display_name="层次相关聚类 (Hierarchical Correlation Clustering)",
        capability_group="correlation_collinearity",
        operation_type="redundancy_filter",
        status="available",
        supported_feature_types=["numeric"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=False,
        fit_scope="dataset_profile_only",
        allowed_pipeline_positions=["before_scaling"],
        parameters_schema={"distance_threshold": {"type": "float", "default": 0.05}},
        default_parameters={"distance_threshold": 0.05},
        risk_notes=["聚类结果依赖距离度量", "可解释性较pair-wise过滤低"],
        fallback_capability_ids=["pearson_correlation_filter"],
        version="1.0.0",
    ),
    FPCapabilitySpec(
        capability_id="representative_feature_selector",
        display_name="代表特征选择器 (Representative Feature Selector)",
        capability_group="correlation_collinearity",
        operation_type="redundancy_filter",
        status="available",
        supported_feature_types=["numeric"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=False,
        fit_scope="dataset_profile_only",
        allowed_pipeline_positions=["before_scaling"],
        parameters_schema={"selection_criterion": {"type": "string", "enum": ["highest_variance", "lowest_missing", "most_interpretable"], "default": "highest_variance"}},
        default_parameters={"selection_criterion": "highest_variance"},
        risk_notes=["选择标准影响最终特征集", "可能丢失材料学关键特征"],
        fallback_capability_ids=["pearson_correlation_filter"],
        version="1.0.0",
    ),
    FPCapabilitySpec(
        capability_id="feature_group_redundancy_analyzer",
        display_name="特征组冗余分析器 (Feature Group Redundancy Analyzer)",
        capability_group="correlation_collinearity",
        operation_type="analysis",
        status="available",
        supported_feature_types=["numeric"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=False,
        fit_scope="dataset_profile_only",
        allowed_pipeline_positions=["before_scaling"],
        parameters_schema={},
        default_parameters={},
        risk_notes=["仅分析不执行操作"],
        fallback_capability_ids=["correlation_pair_reporter"],
        version="1.0.0",
    ),

    # ===== Group 7: Leakage Detection =====
    FPCapabilitySpec(
        capability_id="target_column_excluder",
        display_name="目标列排除器 (Target Column Excluder)",
        capability_group="leakage_detection",
        operation_type="leakage_detection",
        status="available",
        supported_feature_types=["numeric", "categorical"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=True,
        fit_scope="dataset_profile_only",
        allowed_pipeline_positions=["before_scaling"],
        parameters_schema={"target_column": {"type": "string"}},
        default_parameters={},
        risk_notes=["必须始终启用", "P0级别规则"],
        fallback_capability_ids=[],
        version="1.0.0",
    ),
    FPCapabilitySpec(
        capability_id="id_column_dropper",
        display_name="标识列删除器 (ID Column Dropper)",
        capability_group="leakage_detection",
        operation_type="leakage_detection",
        status="available",
        supported_feature_types=["numeric", "categorical"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=False,
        fit_scope="dataset_profile_only",
        allowed_pipeline_positions=["before_scaling"],
        parameters_schema={"id_patterns": {"type": "array", "default": ["id", "ID", "_id", "uuid", "sample_name", "filename", "db_id"]}},
        default_parameters={"id_patterns": ["id", "ID", "_id", "uuid", "sample_name", "filename", "db_id"]},
        risk_notes=["可能误删以'id'结尾的材料标识字段（如'compound_id'）"],
        fallback_capability_ids=[],
        version="1.0.0",
    ),
    FPCapabilitySpec(
        capability_id="metadata_column_detector",
        display_name="元数据列检测器 (Metadata Column Detector)",
        capability_group="leakage_detection",
        operation_type="leakage_detection",
        status="available",
        supported_feature_types=["numeric", "categorical"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=False,
        fit_scope="dataset_profile_only",
        allowed_pipeline_positions=["before_scaling"],
        parameters_schema={},
        default_parameters={},
        risk_notes=["可能将有效特征误标为metadata", "需LLM最终决策"],
        fallback_capability_ids=[],
        version="1.0.0",
    ),
    FPCapabilitySpec(
        capability_id="duplicate_target_column_detector",
        display_name="重复目标列检测器 (Duplicate Target Column Detector)",
        capability_group="leakage_detection",
        operation_type="leakage_detection",
        status="available",
        supported_feature_types=["numeric", "categorical"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=True,
        fit_scope="dataset_profile_only",
        allowed_pipeline_positions=["before_scaling"],
        parameters_schema={},
        default_parameters={},
        risk_notes=["检测高相关（>0.99）的疑似重复目标列"],
        fallback_capability_ids=[],
        version="1.0.0",
    ),
    FPCapabilitySpec(
        capability_id="target_name_similarity_checker",
        display_name="目标名称相似度检查器 (Target Name Similarity Checker)",
        capability_group="leakage_detection",
        operation_type="leakage_detection",
        status="available",
        supported_feature_types=["numeric", "categorical"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=True,
        fit_scope="dataset_profile_only",
        allowed_pipeline_positions=["before_scaling"],
        parameters_schema={"similarity_threshold": {"type": "float", "default": 0.7}},
        default_parameters={"similarity_threshold": 0.7},
        risk_notes=["基于字符串相似度，可能有误报"],
        fallback_capability_ids=[],
        version="1.0.0",
    ),
    FPCapabilitySpec(
        capability_id="target_correlation_leakage_checker",
        display_name="目标相关泄漏检查器 (Target Correlation Leakage Checker)",
        capability_group="leakage_detection",
        operation_type="leakage_detection",
        status="available",
        supported_feature_types=["numeric"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=True,
        fit_scope="dataset_profile_only",
        allowed_pipeline_positions=["before_scaling"],
        parameters_schema={"correlation_threshold": {"type": "float", "default": 0.95}},
        default_parameters={"correlation_threshold": 0.95},
        risk_notes=["高相关不等于因果泄漏", "需LLM结合领域知识判断"],
        fallback_capability_ids=[],
        version="1.0.0",
    ),
    FPCapabilitySpec(
        capability_id="basic_leakage_checker",
        display_name="基础泄漏检查器 (Basic Leakage Checker)",
        capability_group="leakage_detection",
        operation_type="leakage_detection",
        status="available",
        supported_feature_types=["numeric", "categorical"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=True,
        fit_scope="dataset_profile_only",
        allowed_pipeline_positions=["before_scaling"],
        parameters_schema={},
        default_parameters={},
        risk_notes=["轻量级检查", "不替代详尽分析"],
        fallback_capability_ids=[],
        version="1.0.0",
    ),
    FPCapabilitySpec(
        capability_id="leakage_risk_report_builder",
        display_name="泄漏风险报告构建器 (Leakage Risk Report Builder)",
        capability_group="leakage_detection",
        operation_type="leakage_detection",
        status="available",
        supported_feature_types=["numeric", "categorical"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=True,
        fit_scope="dataset_profile_only",
        allowed_pipeline_positions=["before_scaling"],
        parameters_schema={},
        default_parameters={},
        risk_notes=["汇总所有泄漏检测结果", "供下游模块使用"],
        fallback_capability_ids=[],
        version="1.0.0",
    ),

    # ===== Group 8: Feature Selection =====
    FPCapabilitySpec(
        capability_id="variance_threshold_selector",
        display_name="方差阈值选择器 (Variance Threshold Selector)",
        capability_group="feature_selection",
        operation_type="feature_selection",
        status="available",
        supported_feature_types=["numeric"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=False,
        fit_scope="dataset_profile_only",
        allowed_pipeline_positions=["before_scaling", "after_scaling"],
        parameters_schema={"threshold": {"type": "float", "default": 0.0}},
        default_parameters={"threshold": 0.0},
        risk_notes=["需先缩放才能公平比较"],
        fallback_capability_ids=[],
        version="1.0.0",
    ),
    FPCapabilitySpec(
        capability_id="missing_rate_selector",
        display_name="缺失率选择器 (Missing Rate Selector)",
        capability_group="feature_selection",
        operation_type="feature_selection",
        status="available",
        supported_feature_types=["numeric", "categorical", "boolean"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=False,
        fit_scope="dataset_profile_only",
        allowed_pipeline_positions=["before_scaling"],
        parameters_schema={"threshold": {"type": "float", "default": 0.5}},
        default_parameters={"threshold": 0.5},
        risk_notes=["无监督选择，不考虑预测价值"],
        fallback_capability_ids=[],
        version="1.0.0",
    ),
    FPCapabilitySpec(
        capability_id="correlation_selector",
        display_name="相关选择器 (Correlation Selector)",
        capability_group="feature_selection",
        operation_type="feature_selection",
        status="available",
        supported_feature_types=["numeric"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=False,
        fit_scope="dataset_profile_only",
        allowed_pipeline_positions=["before_scaling", "after_scaling"],
        parameters_schema={"threshold": {"type": "float", "default": 0.95}},
        default_parameters={"threshold": 0.95},
        risk_notes=["无监督选择，可能删除预测相关特征"],
        fallback_capability_ids=[],
        version="1.0.0",
    ),
    FPCapabilitySpec(
        capability_id="mutual_information_selector",
        display_name="互信息选择器 (Mutual Information Selector)",
        capability_group="feature_selection",
        operation_type="feature_selection",
        status="available",
        supported_feature_types=["numeric"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=True,
        fit_scope="fold_only",
        allowed_pipeline_positions=["after_imputation", "after_scaling"],
        parameters_schema={"k": {"type": "integer", "default": 50}, "random_state": {"type": "integer", "default": 42}},
        default_parameters={"k": 50, "random_state": 42},
        risk_notes=["target-aware，必须fold-safe", "不得在全量数据fit后用于CV"],
        fallback_capability_ids=["f_regression_selector", "correlation_selector"],
        version="1.0.0",
    ),
    FPCapabilitySpec(
        capability_id="f_regression_selector",
        display_name="F回归选择器 (F-regression Selector)",
        capability_group="feature_selection",
        operation_type="feature_selection",
        status="available",
        supported_feature_types=["numeric"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=True,
        fit_scope="fold_only",
        allowed_pipeline_positions=["after_imputation", "after_scaling"],
        parameters_schema={"k": {"type": "integer", "default": 50}},
        default_parameters={"k": 50},
        risk_notes=["target-aware，必须fold-safe", "假设线性关系"],
        fallback_capability_ids=["mutual_information_selector"],
        version="1.0.0",
    ),
    FPCapabilitySpec(
        capability_id="f_classif_selector",
        display_name="F分类选择器 (F-classif Selector)",
        capability_group="feature_selection",
        operation_type="feature_selection",
        status="available",
        supported_feature_types=["numeric"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=True,
        fit_scope="fold_only",
        allowed_pipeline_positions=["after_imputation", "after_scaling"],
        parameters_schema={"k": {"type": "integer", "default": 50}},
        default_parameters={"k": 50},
        risk_notes=["target-aware，必须fold-safe", "假设方差齐性"],
        fallback_capability_ids=["mutual_information_selector"],
        version="1.0.0",
    ),
    FPCapabilitySpec(
        capability_id="lasso_selector",
        display_name="Lasso选择器 (Lasso Selector)",
        capability_group="feature_selection",
        operation_type="feature_selection",
        status="available",
        supported_feature_types=["numeric"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=True,
        fit_scope="fold_only",
        allowed_pipeline_positions=["after_scaling"],
        parameters_schema={"alpha": {"type": "float", "default": 0.01}, "random_state": {"type": "integer", "default": 42}},
        default_parameters={"alpha": 0.01, "random_state": 42},
        risk_notes=["target-aware，必须fold-safe", "假设线性关系"],
        fallback_capability_ids=["mutual_information_selector"],
        version="1.0.0",
    ),
    FPCapabilitySpec(
        capability_id="elastic_net_selector",
        display_name="ElasticNet选择器 (ElasticNet Selector)",
        capability_group="feature_selection",
        operation_type="feature_selection",
        status="available",
        supported_feature_types=["numeric"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=True,
        fit_scope="fold_only",
        allowed_pipeline_positions=["after_scaling"],
        parameters_schema={"alpha": {"type": "float", "default": 0.01}, "l1_ratio": {"type": "float", "default": 0.5}, "random_state": {"type": "integer", "default": 42}},
        default_parameters={"alpha": 0.01, "l1_ratio": 0.5, "random_state": 42},
        risk_notes=["target-aware，必须fold-safe", "比Lasso更稳定但增加超参"],
        fallback_capability_ids=["lasso_selector", "mutual_information_selector"],
        version="1.0.0",
    ),
    FPCapabilitySpec(
        capability_id="tree_importance_selector",
        display_name="树模型重要性选择器 (Tree Importance Selector)",
        capability_group="feature_selection",
        operation_type="feature_selection",
        status="available",
        supported_feature_types=["numeric"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=True,
        fit_scope="fold_only",
        allowed_pipeline_positions=["after_imputation"],
        parameters_schema={"k": {"type": "integer", "default": 50}, "random_state": {"type": "integer", "default": 42}},
        default_parameters={"k": 50, "random_state": 42},
        risk_notes=["target-aware，必须fold-safe", "树模型重要性可能偏向高基数特征"],
        fallback_capability_ids=["mutual_information_selector"],
        version="1.0.0",
    ),
    FPCapabilitySpec(
        capability_id="recursive_feature_elimination",
        display_name="递归特征消除 (Recursive Feature Elimination)",
        capability_group="feature_selection",
        operation_type="feature_selection",
        status="available",
        supported_feature_types=["numeric"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=True,
        fit_scope="fold_only",
        allowed_pipeline_positions=["after_scaling"],
        parameters_schema={"n_features_to_select": {"type": "integer", "default": 30}},
        default_parameters={"n_features_to_select": 30},
        risk_notes=["target-aware，必须fold-safe", "计算成本较高", "小样本需谨慎"],
        fallback_capability_ids=["mutual_information_selector"],
        version="1.0.0",
    ),
    FPCapabilitySpec(
        capability_id="sequential_feature_selector",
        display_name="序列特征选择器 (Sequential Feature Selector)",
        capability_group="feature_selection",
        operation_type="feature_selection",
        status="available",
        supported_feature_types=["numeric"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=True,
        fit_scope="fold_only",
        allowed_pipeline_positions=["after_scaling"],
        parameters_schema={"n_features_to_select": {"type": "integer", "default": 30}, "direction": {"type": "string", "enum": ["forward", "backward"], "default": "forward"}},
        default_parameters={"n_features_to_select": 30, "direction": "forward"},
        risk_notes=["target-aware，必须fold-safe", "计算成本很高", "仅用于少量特征场景"],
        fallback_capability_ids=["mutual_information_selector", "recursive_feature_elimination"],
        version="1.0.0",
    ),
    FPCapabilitySpec(
        capability_id="max_feature_count_limiter",
        display_name="最大特征数限制器 (Max Feature Count Limiter)",
        capability_group="feature_selection",
        operation_type="feature_selection",
        status="available",
        supported_feature_types=["numeric"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=False,
        fit_scope="dataset_profile_only",
        allowed_pipeline_positions=["after_scaling"],
        parameters_schema={"max_features": {"type": "integer", "default": 500}},
        default_parameters={"max_features": 500},
        risk_notes=["硬限制可能删除有用特征", "与其它选择器联合使用时需注意顺序"],
        fallback_capability_ids=[],
        version="1.0.0",
    ),

    # ===== Group 9: Feature Group Policy =====
    FPCapabilitySpec(
        capability_id="feature_group_allowlist",
        display_name="特征组白名单 (Feature Group Allowlist)",
        capability_group="feature_group_policy",
        operation_type="group_policy",
        status="available",
        supported_feature_types=["numeric", "categorical", "boolean"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=False,
        fit_scope="dataset_profile_only",
        allowed_pipeline_positions=["before_scaling"],
        parameters_schema={"allowlist": {"type": "array", "default": []}},
        default_parameters={"allowlist": []},
        risk_notes=["可能遗漏有价值的非白名单特征组"],
        fallback_capability_ids=[],
        version="1.0.0",
    ),
    FPCapabilitySpec(
        capability_id="feature_group_denylist",
        display_name="特征组黑名单 (Feature Group Denylist)",
        capability_group="feature_group_policy",
        operation_type="group_policy",
        status="available",
        supported_feature_types=["numeric", "categorical", "boolean"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=False,
        fit_scope="dataset_profile_only",
        allowed_pipeline_positions=["before_scaling"],
        parameters_schema={"denylist": {"type": "array", "default": []}},
        default_parameters={"denylist": []},
        risk_notes=["可能过度排除特征组"],
        fallback_capability_ids=[],
        version="1.0.0",
    ),
    FPCapabilitySpec(
        capability_id="feature_group_priority_policy",
        display_name="特征组优先级策略 (Feature Group Priority Policy)",
        capability_group="feature_group_policy",
        operation_type="group_policy",
        status="available",
        supported_feature_types=["numeric", "categorical", "boolean"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=False,
        fit_scope="dataset_profile_only",
        allowed_pipeline_positions=["before_scaling"],
        parameters_schema={"priority_order": {"type": "array", "default": []}},
        default_parameters={"priority_order": []},
        risk_notes=["优先级设置需要材料学领域知识"],
        fallback_capability_ids=[],
        version="1.0.0",
    ),
    FPCapabilitySpec(
        capability_id="feature_group_specific_pipeline",
        display_name="特征组特定管道 (Feature Group Specific Pipeline)",
        capability_group="feature_group_policy",
        operation_type="group_policy",
        status="available",
        supported_feature_types=["numeric", "categorical", "boolean"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=False,
        fit_scope="fold_only",
        allowed_pipeline_positions=["before_scaling", "after_imputation"],
        parameters_schema={"per_group_operations": {"type": "object", "default": {}}},
        default_parameters={"per_group_operations": {}},
        risk_notes=["增加pipeline复杂度", "必须fold-safe"],
        fallback_capability_ids=["feature_group_priority_policy"],
        version="1.0.0",
    ),
    FPCapabilitySpec(
        capability_id="feature_group_quality_ranker",
        display_name="特征组质量排序器 (Feature Group Quality Ranker)",
        capability_group="feature_group_policy",
        operation_type="group_policy",
        status="available",
        supported_feature_types=["numeric", "categorical", "boolean"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=False,
        fit_scope="dataset_profile_only",
        allowed_pipeline_positions=["before_scaling"],
        parameters_schema={},
        default_parameters={},
        risk_notes=["质量排序为依据缺失率/方差/相关性综合评分"],
        fallback_capability_ids=[],
        version="1.0.0",
    ),
    FPCapabilitySpec(
        capability_id="feature_group_preservation_policy",
        display_name="特征组保护策略 (Feature Group Preservation Policy)",
        capability_group="feature_group_policy",
        operation_type="group_policy",
        status="available",
        supported_feature_types=["numeric", "categorical", "boolean"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=False,
        fit_scope="dataset_profile_only",
        allowed_pipeline_positions=["before_scaling"],
        parameters_schema={"preserved_groups": {"type": "array", "default": []}, "preservation_rationale": {"type": "string", "default": ""}},
        default_parameters={"preserved_groups": [], "preservation_rationale": ""},
        risk_notes=["保护低质量但可解释性重要的特征组"],
        fallback_capability_ids=[],
        version="1.0.0",
    ),

    # ===== Group 10: Dimensionality Reduction =====
    FPCapabilitySpec(
        capability_id="pca_transform",
        display_name="PCA降维 (PCA Transform)",
        capability_group="dimensionality_reduction",
        operation_type="dimensionality_reduction",
        status="available",
        supported_feature_types=["numeric"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=False,
        fit_scope="fold_only",
        allowed_pipeline_positions=["after_scaling"],
        parameters_schema={"n_components": {"type": "integer", "minimum": 1, "default": 10}, "random_state": {"type": "integer", "default": 42}},
        default_parameters={"n_components": 10, "random_state": 42},
        risk_notes=["降低可解释性（特征变为线性组合）", "必须fold-safe", "需先缩放"],
        fallback_capability_ids=["incremental_pca_transform"],
        version="1.0.0",
    ),
    FPCapabilitySpec(
        capability_id="incremental_pca_transform",
        display_name="增量PCA降维 (Incremental PCA Transform)",
        capability_group="dimensionality_reduction",
        operation_type="dimensionality_reduction",
        status="available",
        supported_feature_types=["numeric"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=False,
        fit_scope="fold_only",
        allowed_pipeline_positions=["after_scaling"],
        parameters_schema={"n_components": {"type": "integer", "default": 10}, "batch_size": {"type": "integer", "default": 200}},
        default_parameters={"n_components": 10, "batch_size": 200},
        risk_notes=["适用于大数据集", "必须fold-safe", "同样降低可解释性"],
        fallback_capability_ids=["pca_transform"],
        version="1.0.0",
    ),
    FPCapabilitySpec(
        capability_id="truncated_svd_transform",
        display_name="截断SVD降维 (Truncated SVD Transform)",
        capability_group="dimensionality_reduction",
        operation_type="dimensionality_reduction",
        status="available",
        supported_feature_types=["numeric"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=False,
        fit_scope="fold_only",
        allowed_pipeline_positions=["after_imputation"],
        parameters_schema={"n_components": {"type": "integer", "default": 10}, "random_state": {"type": "integer", "default": 42}},
        default_parameters={"n_components": 10, "random_state": 42},
        risk_notes=["适用于稀疏矩阵", "无需先缩放", "必须fold-safe", "降低可解释性"],
        fallback_capability_ids=["pca_transform"],
        version="1.0.0",
    ),
    FPCapabilitySpec(
        capability_id="feature_group_pca",
        display_name="特征组PCA (Feature Group PCA)",
        capability_group="dimensionality_reduction",
        operation_type="dimensionality_reduction",
        status="available",
        supported_feature_types=["numeric"],
        supported_feature_groups=["composition", "structure", "descriptor"],
        requires_target=False,
        fit_scope="fold_only",
        allowed_pipeline_positions=["after_scaling"],
        parameters_schema={"n_components_per_group": {"type": "integer", "default": 5}},
        default_parameters={"n_components_per_group": 5},
        risk_notes=["按feature group分别降维保留部分可解释性", "必须fold-safe"],
        fallback_capability_ids=["pca_transform"],
        version="1.0.0",
    ),
    FPCapabilitySpec(
        capability_id="dimension_reduction_policy_builder",
        display_name="降维策略构建器 (Dimension Reduction Policy Builder)",
        capability_group="dimensionality_reduction",
        operation_type="dimensionality_reduction",
        status="available",
        supported_feature_types=["numeric"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=False,
        fit_scope="dataset_profile_only",
        allowed_pipeline_positions=["before_scaling"],
        parameters_schema={},
        default_parameters={},
        risk_notes=["仅构建策略不执行降维", "供LLM决策参考"],
        fallback_capability_ids=[],
        version="1.0.0",
    ),

    # ===== Group 11: Interpretability Preservation =====
    FPCapabilitySpec(
        capability_id="interpretability_preserving_selector",
        display_name="可解释性保护选择器 (Interpretability Preserving Selector)",
        capability_group="interpretability_preservation",
        operation_type="lineage",
        status="available",
        supported_feature_types=["numeric", "categorical", "boolean"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=False,
        fit_scope="dataset_profile_only",
        allowed_pipeline_positions=["before_scaling"],
        parameters_schema={"protect_interpretable_groups": {"type": "boolean", "default": True}},
        default_parameters={"protect_interpretable_groups": True},
        risk_notes=["可能保留冗余但可解释的特征"],
        fallback_capability_ids=[],
        version="1.0.0",
    ),
    FPCapabilitySpec(
        capability_id="feature_name_lineage_tracker",
        display_name="特征名沿袭追踪器 (Feature Name Lineage Tracker)",
        capability_group="interpretability_preservation",
        operation_type="lineage",
        status="available",
        supported_feature_types=["numeric", "categorical", "boolean"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=False,
        fit_scope="dataset_profile_only",
        allowed_pipeline_positions=["before_scaling", "after_imputation", "after_scaling", "after_transformation"],
        parameters_schema={},
        default_parameters={},
        risk_notes=["追踪所有操作的特征名变化"],
        fallback_capability_ids=[],
        version="1.0.0",
    ),
    FPCapabilitySpec(
        capability_id="transformed_feature_name_generator",
        display_name="变换后特征名生成器 (Transformed Feature Name Generator)",
        capability_group="interpretability_preservation",
        operation_type="lineage",
        status="available",
        supported_feature_types=["numeric", "categorical"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=False,
        fit_scope="dataset_profile_only",
        allowed_pipeline_positions=["after_imputation", "after_scaling", "after_transformation"],
        parameters_schema={"naming_pattern": {"type": "string", "default": "{original}_{transform}"}},
        default_parameters={"naming_pattern": "{original}_{transform}"},
        risk_notes=["命名规范需要保持一致"],
        fallback_capability_ids=[],
        version="1.0.0",
    ),
    FPCapabilitySpec(
        capability_id="feature_group_lineage_tracker",
        display_name="特征组沿袭追踪器 (Feature Group Lineage Tracker)",
        capability_group="interpretability_preservation",
        operation_type="lineage",
        status="available",
        supported_feature_types=["numeric", "categorical", "boolean"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=False,
        fit_scope="dataset_profile_only",
        allowed_pipeline_positions=["before_scaling", "after_imputation", "after_scaling", "after_transformation"],
        parameters_schema={},
        default_parameters={},
        risk_notes=["追踪特征组级别的沿袭"],
        fallback_capability_ids=[],
        version="1.0.0",
    ),
    FPCapabilitySpec(
        capability_id="post_preprocessing_explainability_reporter",
        display_name="预处理后可解释性报告 (Post-Preprocessing Explainability Reporter)",
        capability_group="interpretability_preservation",
        operation_type="lineage",
        status="available",
        supported_feature_types=["numeric", "categorical", "boolean"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=False,
        fit_scope="dataset_profile_only",
        allowed_pipeline_positions=["after_scaling", "after_transformation"],
        parameters_schema={},
        default_parameters={},
        risk_notes=["汇总所有可解释性相关信息"],
        fallback_capability_ids=[],
        version="1.0.0",
    ),

    # ===== Group 12: Artifact & Reproducibility =====
    FPCapabilitySpec(
        capability_id="preprocessing_plan_snapshot",
        display_name="预处理计划快照 (Preprocessing Plan Snapshot)",
        capability_group="artifact_reproducibility",
        operation_type="artifact_tracking",
        status="available",
        supported_feature_types=["numeric", "categorical", "boolean"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=False,
        fit_scope="dataset_profile_only",
        allowed_pipeline_positions=[],
        parameters_schema={},
        default_parameters={},
        risk_notes=[],
        fallback_capability_ids=[],
        version="1.0.0",
    ),
    FPCapabilitySpec(
        capability_id="preprocessing_registry_snapshot",
        display_name="预处理registry快照 (Preprocessing Registry Snapshot)",
        capability_group="artifact_reproducibility",
        operation_type="artifact_tracking",
        status="available",
        supported_feature_types=["numeric", "categorical", "boolean"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=False,
        fit_scope="dataset_profile_only",
        allowed_pipeline_positions=[],
        parameters_schema={},
        default_parameters={},
        risk_notes=[],
        fallback_capability_ids=[],
        version="1.0.0",
    ),
    FPCapabilitySpec(
        capability_id="input_feature_artifact_hash",
        display_name="输入特征artifact哈希 (Input Feature Artifact Hash)",
        capability_group="artifact_reproducibility",
        operation_type="artifact_tracking",
        status="available",
        supported_feature_types=["numeric", "categorical", "boolean"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=False,
        fit_scope="dataset_profile_only",
        allowed_pipeline_positions=[],
        parameters_schema={},
        default_parameters={},
        risk_notes=[],
        fallback_capability_ids=[],
        version="1.0.0",
    ),
    FPCapabilitySpec(
        capability_id="output_artifact_hash",
        display_name="输出artifact哈希 (Output Artifact Hash)",
        capability_group="artifact_reproducibility",
        operation_type="artifact_tracking",
        status="available",
        supported_feature_types=["numeric", "categorical", "boolean"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=False,
        fit_scope="dataset_profile_only",
        allowed_pipeline_positions=[],
        parameters_schema={},
        default_parameters={},
        risk_notes=[],
        fallback_capability_ids=[],
        version="1.0.0",
    ),
    FPCapabilitySpec(
        capability_id="operation_parameter_snapshot",
        display_name="操作参数快照 (Operation Parameter Snapshot)",
        capability_group="artifact_reproducibility",
        operation_type="artifact_tracking",
        status="available",
        supported_feature_types=["numeric", "categorical", "boolean"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=False,
        fit_scope="dataset_profile_only",
        allowed_pipeline_positions=[],
        parameters_schema={},
        default_parameters={},
        risk_notes=[],
        fallback_capability_ids=[],
        version="1.0.0",
    ),
    FPCapabilitySpec(
        capability_id="fitted_statistics_summary",
        display_name="拟合统计摘要 (Fitted Statistics Summary)",
        capability_group="artifact_reproducibility",
        operation_type="artifact_tracking",
        status="available",
        supported_feature_types=["numeric", "categorical", "boolean"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=False,
        fit_scope="dataset_profile_only",
        allowed_pipeline_positions=[],
        parameters_schema={},
        default_parameters={},
        risk_notes=[],
        fallback_capability_ids=[],
        version="1.0.0",
    ),
    FPCapabilitySpec(
        capability_id="removed_feature_report",
        display_name="已删除特征报告 (Removed Feature Report)",
        capability_group="artifact_reproducibility",
        operation_type="artifact_tracking",
        status="available",
        supported_feature_types=["numeric", "categorical", "boolean"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=False,
        fit_scope="dataset_profile_only",
        allowed_pipeline_positions=[],
        parameters_schema={},
        default_parameters={},
        risk_notes=[],
        fallback_capability_ids=[],
        version="1.0.0",
    ),
    FPCapabilitySpec(
        capability_id="retained_feature_report",
        display_name="已保留特征报告 (Retained Feature Report)",
        capability_group="artifact_reproducibility",
        operation_type="artifact_tracking",
        status="available",
        supported_feature_types=["numeric", "categorical", "boolean"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=False,
        fit_scope="dataset_profile_only",
        allowed_pipeline_positions=[],
        parameters_schema={},
        default_parameters={},
        risk_notes=[],
        fallback_capability_ids=[],
        version="1.0.0",
    ),
    FPCapabilitySpec(
        capability_id="random_seed_recorder",
        display_name="随机种子记录器 (Random Seed Recorder)",
        capability_group="artifact_reproducibility",
        operation_type="artifact_tracking",
        status="available",
        supported_feature_types=["numeric", "categorical", "boolean"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=False,
        fit_scope="dataset_profile_only",
        allowed_pipeline_positions=[],
        parameters_schema={"random_seed": {"type": "integer", "default": 42}},
        default_parameters={"random_seed": 42},
        risk_notes=[],
        fallback_capability_ids=[],
        version="1.0.0",
    ),
    FPCapabilitySpec(
        capability_id="dependency_version_recorder",
        display_name="依赖版本记录器 (Dependency Version Recorder)",
        capability_group="artifact_reproducibility",
        operation_type="artifact_tracking",
        status="available",
        supported_feature_types=["numeric", "categorical", "boolean"],
        supported_feature_groups=["composition", "structure", "descriptor", "metadata", "generated"],
        requires_target=False,
        fit_scope="dataset_profile_only",
        allowed_pipeline_positions=[],
        parameters_schema={},
        default_parameters={},
        risk_notes=[],
        fallback_capability_ids=[],
        version="1.0.0",
    ),
]

# Fast lookup
FP_CAPABILITY_BY_ID: Dict[str, FPCapabilitySpec] = {
    c.capability_id: c for c in PREPROCESSING_CAPABILITIES
}


def get_available_fp_capabilities(
    capability_group: Optional[str] = None,
    operation_type: Optional[str] = None,
) -> List[FPCapabilitySpec]:
    """Return FP capabilities with status='available', optionally filtered by group or type."""
    result = [c for c in PREPROCESSING_CAPABILITIES if c.status == "available"]
    if capability_group:
        result = [c for c in result if c.capability_group == capability_group]
    if operation_type:
        result = [c for c in result if c.operation_type == operation_type]
    return result


def get_all_fp_capabilities(status: Optional[str] = None) -> List[FPCapabilitySpec]:
    """Return all FP capabilities, optionally filtered by status."""
    if status:
        return [c for c in PREPROCESSING_CAPABILITIES if c.status == status]
    return list(PREPROCESSING_CAPABILITIES)


def get_fp_capability_by_id(capability_id: str) -> Optional[FPCapabilitySpec]:
    """Look up a single FP capability by its ID."""
    return FP_CAPABILITY_BY_ID.get(capability_id)


def get_registry_snapshot_fp() -> Dict[str, Any]:
    """Return a lightweight snapshot for persistence."""
    import datetime
    return {
        "snapshot_version": "1.0.0",
        "created_at": datetime.datetime.now().isoformat(),
        "total_capabilities": len(PREPROCESSING_CAPABILITIES),
        "available_count": len([c for c in PREPROCESSING_CAPABILITIES if c.status == "available"]),
        "capability_groups": {
            k: len([c for c in PREPROCESSING_CAPABILITIES if c.capability_group == k and c.status == "available"])
            for k in CAPABILITY_GROUPS
        },
        "capabilities": [c.model_dump() for c in PREPROCESSING_CAPABILITIES],
    }
