"""add_iteration_decision_and_update_fps

Revision ID: 3578774de4dc
Revises: 9a9e685ec64b
Create Date: 2026-05-23 13:58:48.763305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3578774de4dc'
down_revision: Union[str, None] = '9a9e685ec64b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iteration_decision',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('task_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('metric_evaluation_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('pipeline_execution_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('source_workflow_plan_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('iteration_index', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('decision', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('decision_confidence', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('reasoning_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rerun_from_stage', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('revised_workflow_plan_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('iteration_rerun_plan_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ready_for_iteration', sa.Boolean(), nullable=True),
    sa.Column('stop_rationale_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('final_pipeline_selection_input_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ready_for_final_selection', sa.Boolean(), nullable=True),
    sa.Column('evidence_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('system_checks_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('llm_request_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('llm_response_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('validation_result_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('artifact_dir', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_iteration_decision_created_at'), 'iteration_decision', ['created_at'], unique=False)
    op.create_index(op.f('ix_iteration_decision_decision'), 'iteration_decision', ['decision'], unique=False)
    op.create_index(op.f('ix_iteration_decision_iteration_index'), 'iteration_decision', ['iteration_index'], unique=False)
    op.create_index(op.f('ix_iteration_decision_metric_evaluation_id'), 'iteration_decision', ['metric_evaluation_id'], unique=False)
    op.create_index(op.f('ix_iteration_decision_status'), 'iteration_decision', ['status'], unique=False)
    op.create_index(op.f('ix_iteration_decision_task_id'), 'iteration_decision', ['task_id'], unique=False)
    op.drop_index('ix_workflow_refinement_created_at', table_name='workflow_refinement')
    op.drop_index('ix_workflow_refinement_decision', table_name='workflow_refinement')
    op.drop_index('ix_workflow_refinement_iteration_index', table_name='workflow_refinement')
    op.drop_index('ix_workflow_refinement_metric_evaluation_id', table_name='workflow_refinement')
    op.drop_index('ix_workflow_refinement_pipeline_execution_id', table_name='workflow_refinement')
    op.drop_index('ix_workflow_refinement_ready_for_final_pipeline_selection', table_name='workflow_refinement')
    op.drop_index('ix_workflow_refinement_ready_for_iteration', table_name='workflow_refinement')
    op.drop_index('ix_workflow_refinement_recommended_rerun_from_stage', table_name='workflow_refinement')
    op.drop_index('ix_workflow_refinement_result_diagnosis_id', table_name='workflow_refinement')
    op.drop_index('ix_workflow_refinement_source_workflow_plan_id', table_name='workflow_refinement')
    op.drop_index('ix_workflow_refinement_status', table_name='workflow_refinement')
    op.drop_index('ix_workflow_refinement_task_id', table_name='workflow_refinement')
    op.drop_table('workflow_refinement')
    op.drop_index('ix_result_diagnosis_created_at', table_name='result_diagnosis')
    op.drop_index('ix_result_diagnosis_diagnosis_mode', table_name='result_diagnosis')
    op.drop_index('ix_result_diagnosis_main_issue_category', table_name='result_diagnosis')
    op.drop_index('ix_result_diagnosis_metric_evaluation_id', table_name='result_diagnosis')
    op.drop_index('ix_result_diagnosis_performance_level', table_name='result_diagnosis')
    op.drop_index('ix_result_diagnosis_pipeline_execution_id', table_name='result_diagnosis')
    op.drop_index('ix_result_diagnosis_ready_for_closed_loop_refinement', table_name='result_diagnosis')
    op.drop_index('ix_result_diagnosis_should_refine', table_name='result_diagnosis')
    op.drop_index('ix_result_diagnosis_status', table_name='result_diagnosis')
    op.drop_index('ix_result_diagnosis_task_id', table_name='result_diagnosis')
    op.drop_table('result_diagnosis')
    op.add_column('final_pipeline_selection', sa.Column('iteration_decision_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.drop_index('ix_final_pipeline_selection_workflow_refinement_id', table_name='final_pipeline_selection')
    op.create_index(op.f('ix_final_pipeline_selection_iteration_decision_id'), 'final_pipeline_selection', ['iteration_decision_id'], unique=False)
    op.drop_column('final_pipeline_selection', 'workflow_refinement_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('final_pipeline_selection', sa.Column('workflow_refinement_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_final_pipeline_selection_iteration_decision_id'), table_name='final_pipeline_selection')
    op.create_index('ix_final_pipeline_selection_workflow_refinement_id', 'final_pipeline_selection', ['workflow_refinement_id'], unique=False)
    op.drop_column('final_pipeline_selection', 'iteration_decision_id')
    op.create_table('result_diagnosis',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('metric_evaluation_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('pipeline_execution_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('diagnosis_mode', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('main_issue_category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('performance_level', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('should_refine', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('ready_for_closed_loop_refinement', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('llm_used', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('llm_confidence_level', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('diagnosis_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('closed_loop_refinement_input_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('llm_request_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('llm_response_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('system_checks_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('diagnosis_artifact_dir', sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='result_diagnosis_pkey')
    )
    op.create_index('ix_result_diagnosis_task_id', 'result_diagnosis', ['task_id'], unique=False)
    op.create_index('ix_result_diagnosis_status', 'result_diagnosis', ['status'], unique=False)
    op.create_index('ix_result_diagnosis_should_refine', 'result_diagnosis', ['should_refine'], unique=False)
    op.create_index('ix_result_diagnosis_ready_for_closed_loop_refinement', 'result_diagnosis', ['ready_for_closed_loop_refinement'], unique=False)
    op.create_index('ix_result_diagnosis_pipeline_execution_id', 'result_diagnosis', ['pipeline_execution_id'], unique=False)
    op.create_index('ix_result_diagnosis_performance_level', 'result_diagnosis', ['performance_level'], unique=False)
    op.create_index('ix_result_diagnosis_metric_evaluation_id', 'result_diagnosis', ['metric_evaluation_id'], unique=False)
    op.create_index('ix_result_diagnosis_main_issue_category', 'result_diagnosis', ['main_issue_category'], unique=False)
    op.create_index('ix_result_diagnosis_diagnosis_mode', 'result_diagnosis', ['diagnosis_mode'], unique=False)
    op.create_index('ix_result_diagnosis_created_at', 'result_diagnosis', ['created_at'], unique=False)
    op.create_table('workflow_refinement',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('result_diagnosis_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('metric_evaluation_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('pipeline_execution_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('source_workflow_plan_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('iteration_index', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('decision', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('recommended_rerun_from_stage', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('ready_for_iteration', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('ready_for_final_pipeline_selection', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('decision_confidence_level', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('workflow_refinement_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('revised_workflow_plan_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('workflow_plan_delta_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('iteration_rerun_plan_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('final_pipeline_selection_input_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('llm_request_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('llm_response_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('validation_result_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('artifact_dir', sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='workflow_refinement_pkey')
    )
    op.create_index('ix_workflow_refinement_task_id', 'workflow_refinement', ['task_id'], unique=False)
    op.create_index('ix_workflow_refinement_status', 'workflow_refinement', ['status'], unique=False)
    op.create_index('ix_workflow_refinement_source_workflow_plan_id', 'workflow_refinement', ['source_workflow_plan_id'], unique=False)
    op.create_index('ix_workflow_refinement_result_diagnosis_id', 'workflow_refinement', ['result_diagnosis_id'], unique=False)
    op.create_index('ix_workflow_refinement_recommended_rerun_from_stage', 'workflow_refinement', ['recommended_rerun_from_stage'], unique=False)
    op.create_index('ix_workflow_refinement_ready_for_iteration', 'workflow_refinement', ['ready_for_iteration'], unique=False)
    op.create_index('ix_workflow_refinement_ready_for_final_pipeline_selection', 'workflow_refinement', ['ready_for_final_pipeline_selection'], unique=False)
    op.create_index('ix_workflow_refinement_pipeline_execution_id', 'workflow_refinement', ['pipeline_execution_id'], unique=False)
    op.create_index('ix_workflow_refinement_metric_evaluation_id', 'workflow_refinement', ['metric_evaluation_id'], unique=False)
    op.create_index('ix_workflow_refinement_iteration_index', 'workflow_refinement', ['iteration_index'], unique=False)
    op.create_index('ix_workflow_refinement_decision', 'workflow_refinement', ['decision'], unique=False)
    op.create_index('ix_workflow_refinement_created_at', 'workflow_refinement', ['created_at'], unique=False)
    op.drop_index(op.f('ix_iteration_decision_task_id'), table_name='iteration_decision')
    op.drop_index(op.f('ix_iteration_decision_status'), table_name='iteration_decision')
    op.drop_index(op.f('ix_iteration_decision_metric_evaluation_id'), table_name='iteration_decision')
    op.drop_index(op.f('ix_iteration_decision_iteration_index'), table_name='iteration_decision')
    op.drop_index(op.f('ix_iteration_decision_decision'), table_name='iteration_decision')
    op.drop_index(op.f('ix_iteration_decision_created_at'), table_name='iteration_decision')
    op.drop_table('iteration_decision')
    # ### end Alembic commands ###
