"""initial_schema

Revision ID: 9a9e685ec64b
Revises: 
Create Date: 2026-05-18 18:27:00.828423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9a9e685ec64b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_closed_loop_refinement_created_at', table_name='closed_loop_refinement')
    op.drop_index('ix_closed_loop_refinement_iteration_index', table_name='closed_loop_refinement')
    op.drop_index('ix_closed_loop_refinement_metric_evaluation_id', table_name='closed_loop_refinement')
    op.drop_index('ix_closed_loop_refinement_pipeline_execution_id', table_name='closed_loop_refinement')
    op.drop_index('ix_closed_loop_refinement_primary_refinement_focus', table_name='closed_loop_refinement')
    op.drop_index('ix_closed_loop_refinement_ready_for_final_pipeline_selection', table_name='closed_loop_refinement')
    op.drop_index('ix_closed_loop_refinement_ready_for_next_iteration', table_name='closed_loop_refinement')
    op.drop_index('ix_closed_loop_refinement_refinement_mode', table_name='closed_loop_refinement')
    op.drop_index('ix_closed_loop_refinement_result_diagnosis_id', table_name='closed_loop_refinement')
    op.drop_index('ix_closed_loop_refinement_should_continue_iteration', table_name='closed_loop_refinement')
    op.drop_index('ix_closed_loop_refinement_status', table_name='closed_loop_refinement')
    op.drop_index('ix_closed_loop_refinement_task_id', table_name='closed_loop_refinement')
    op.drop_table('closed_loop_refinement')
    op.drop_index('ix_model_search_context_ready_for_model_search_plan', table_name='model_search_context')
    op.create_index(op.f('ix_model_search_context_ready_for_pipeline_generation'), 'model_search_context', ['ready_for_pipeline_generation'], unique=False)
    op.add_column('pipeline_generation', sa.Column('model_search_context_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.drop_index('ix_pipeline_generation_model_search_plan_id', table_name='pipeline_generation')
    op.create_index(op.f('ix_pipeline_generation_model_search_context_id'), 'pipeline_generation', ['model_search_context_id'], unique=False)
    op.drop_column('pipeline_generation', 'model_search_plan_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline_generation', sa.Column('model_search_plan_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_pipeline_generation_model_search_context_id'), table_name='pipeline_generation')
    op.create_index('ix_pipeline_generation_model_search_plan_id', 'pipeline_generation', ['model_search_plan_id'], unique=False)
    op.drop_column('pipeline_generation', 'model_search_context_id')
    op.drop_index(op.f('ix_model_search_context_ready_for_pipeline_generation'), table_name='model_search_context')
    op.create_index('ix_model_search_context_ready_for_model_search_plan', 'model_search_context', ['ready_for_pipeline_generation'], unique=False)
    op.create_table('closed_loop_refinement',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('result_diagnosis_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('metric_evaluation_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('pipeline_execution_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('iteration_index', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('refinement_mode', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('primary_refinement_focus', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('should_continue_iteration', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('ready_for_next_iteration', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('ready_for_final_pipeline_selection', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('stop_reason', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('llm_used', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('llm_confidence_level', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('refinement_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('next_iteration_plan_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('strategy_delta_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('final_pipeline_selection_input_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('llm_request_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('llm_response_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('system_checks_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('artifact_dir', sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='closed_loop_refinement_pkey')
    )
    op.create_index('ix_closed_loop_refinement_task_id', 'closed_loop_refinement', ['task_id'], unique=False)
    op.create_index('ix_closed_loop_refinement_status', 'closed_loop_refinement', ['status'], unique=False)
    op.create_index('ix_closed_loop_refinement_should_continue_iteration', 'closed_loop_refinement', ['should_continue_iteration'], unique=False)
    op.create_index('ix_closed_loop_refinement_result_diagnosis_id', 'closed_loop_refinement', ['result_diagnosis_id'], unique=False)
    op.create_index('ix_closed_loop_refinement_refinement_mode', 'closed_loop_refinement', ['refinement_mode'], unique=False)
    op.create_index('ix_closed_loop_refinement_ready_for_next_iteration', 'closed_loop_refinement', ['ready_for_next_iteration'], unique=False)
    op.create_index('ix_closed_loop_refinement_ready_for_final_pipeline_selection', 'closed_loop_refinement', ['ready_for_final_pipeline_selection'], unique=False)
    op.create_index('ix_closed_loop_refinement_primary_refinement_focus', 'closed_loop_refinement', ['primary_refinement_focus'], unique=False)
    op.create_index('ix_closed_loop_refinement_pipeline_execution_id', 'closed_loop_refinement', ['pipeline_execution_id'], unique=False)
    op.create_index('ix_closed_loop_refinement_metric_evaluation_id', 'closed_loop_refinement', ['metric_evaluation_id'], unique=False)
    op.create_index('ix_closed_loop_refinement_iteration_index', 'closed_loop_refinement', ['iteration_index'], unique=False)
    op.create_index('ix_closed_loop_refinement_created_at', 'closed_loop_refinement', ['created_at'], unique=False)
    # ### end Alembic commands ###
